from django.db import models

class TotalCost(models.Model):
    u21 = models.CharField(max_length=100, blank=True, null=True)
    ru21 = models.DecimalField(max_digits=10, decimal_places=2, blank=True, null=True)
    u22 = models.CharField(max_length=100, blank=True, null=True)
    ru22 = models.DecimalField(max_digits=10, decimal_places=2, blank=True, null=True)
    u23 = models.CharField(max_length=100, blank=True, null=True)
    ru23 = models.DecimalField(max_digits=10, decimal_places=2, blank=True, null=True)
    u24 = models.CharField(max_length=100, blank=True, null=True)
    ru24 = models.DecimalField(max_digits=10, decimal_places=2, blank=True, null=True)
    u25 = models.CharField(max_length=100, blank=True, null=True)
    ru25 = models.DecimalField(max_digits=10, decimal_places=2, blank=True, null=True)
    u26 = models.CharField(max_length=100, blank=True, null=True)
    ru26 = models.DecimalField(max_digits=10, decimal_places=2, blank=True, null=True)
    u31 = models.CharField(max_length=100, blank=True, null=True)
    ru31 = models.DecimalField(max_digits=10, decimal_places=2, blank=True, null=True)
    u32 = models.CharField(max_length=100, blank=True, null=True)
    ru32 = models.DecimalField(max_digits=10, decimal_places=2, blank=True, null=True)
    u33 = models.CharField(max_length=100, blank=True, null=True)
    ru33 = models.DecimalField(max_digits=10, decimal_places=2, blank=True, null=True)
    u34 = models.CharField(max_length=100, blank=True, null=True)
    ru34 = models.DecimalField(max_digits=10, decimal_places=2, blank=True, null=True)
    u35 = models.CharField(max_length=100, blank=True, null=True)
    ru35 = models.DecimalField(max_digits=10, decimal_places=2, blank=True, null=True)
    u37 = models.CharField(max_length=100, blank=True, null=True)
    ru37 = models.DecimalField(max_digits=10, decimal_places=2, blank=True, null=True)
    u41 = models.CharField(max_length=100, blank=True, null=True)
    ru41 = models.DecimalField(max_digits=10, decimal_places=2, blank=True, null=True)
    u43 = models.CharField(max_length=100, blank=True, null=True)
    ru43 = models.DecimalField(max_digits=10, decimal_places=2, blank=True, null=True)
    u44 = models.CharField(max_length=100, blank=True, null=True)
    ru44 = models.DecimalField(max_digits=10, decimal_places=2, blank=True, null=True)
    u51 = models.CharField(max_length=100, blank=True, null=True)
    ru51 = models.DecimalField(max_digits=10, decimal_places=2, blank=True, null=True)
    u52 = models.CharField(max_length=100, blank=True, null=True)
    ru52 = models.DecimalField(max_digits=10, decimal_places=2, blank=True, null=True)
    u57 = models.CharField(max_length=100, blank=True, null=True)
    ru57 = models.DecimalField(max_digits=10, decimal_places=2, blank=True, null=True)
    u58 = models.CharField(max_length=100, blank=True, null=True)
    ru58 = models.DecimalField(max_digits=10, decimal_places=2, blank=True, null=True)
    u61 = models.CharField(max_length=100, blank=True, null=True)
    ru61 = models.DecimalField(max_digits=10, decimal_places=2, blank=True, null=True)
    u63 = models.CharField(max_length=100, blank=True, null=True)
    ru63 = models.DecimalField(max_digits=10, decimal_places=2, blank=True, null=True)
    u64 = models.CharField(max_length=100, blank=True, null=True)
    ru64 = models.DecimalField(max_digits=10, decimal_places=2, blank=True, null=True)
    u65 = models.CharField(max_length=100, blank=True, null=True)
    ru65 = models.DecimalField(max_digits=10, decimal_places=2, blank=True, null=True)
    u71 = models.CharField(max_length=100, blank=True, null=True)
    ru71 = models.DecimalField(max_digits=10, decimal_places=2, blank=True, null=True)
    u72 = models.CharField(max_length=100, blank=True, null=True)
    ru72 = models.DecimalField(max_digits=10, decimal_places=2, blank=True, null=True)
    u73 = models.CharField(max_length=100, blank=True, null=True)
    ru73 = models.DecimalField(max_digits=10, decimal_places=2, blank=True, null=True)
    u74 = models.CharField(max_length=100, blank=True, null=True)
    ru74 = models.DecimalField(max_digits=10, decimal_places=2, blank=True, null=True)
    u81 = models.CharField(max_length=100, blank=True, null=True)
    ru81 = models.DecimalField(max_digits=10, decimal_places=2, blank=True, null=True)
    u82 = models.CharField(max_length=100, blank=True, null=True)
    ru82 = models.DecimalField(max_digits=10, decimal_places=2, blank=True, null=True)
    u83 = models.CharField(max_length=100, blank=True, null=True)
    ru83 = models.DecimalField(max_digits=10, decimal_places=2, blank=True, null=True)
    u84 = models.CharField(max_length=100, blank=True, null=True)
    ru84 = models.DecimalField(max_digits=10, decimal_places=2, blank=True, null=True)
    u91 = models.CharField(max_length=100, blank=True, null=True)
    ru91 = models.DecimalField(max_digits=10, decimal_places=2, blank=True, null=True)
    u92 = models.CharField(max_length=100, blank=True, null=True)
    ru92 = models.DecimalField(max_digits=10, decimal_places=2, blank=True, null=True)
    u93 = models.CharField(max_length=100, blank=True, null=True)
    ru93 = models.DecimalField(max_digits=10, decimal_places=2, blank=True, null=True)
    u94 = models.CharField(max_length=100, blank=True, null=True)
    ru94 = models.DecimalField(max_digits=10, decimal_places=2, blank=True, null=True)
    u95 = models.CharField(max_length=100, blank=True, null=True)
    ru95 = models.DecimalField(max_digits=10, decimal_places=2, blank=True, null=True)
    u96 = models.CharField(max_length=100, blank=True, null=True)
    ru96 = models.DecimalField(max_digits=10, decimal_places=2, blank=True, null=True)
    u97 = models.CharField(max_length=100, blank=True, null=True)
    ru97 = models.DecimalField(max_digits=10, decimal_places=2, blank=True, null=True)
    ru1a = models.DecimalField(max_digits=10, decimal_places=2, blank=True, null=True)
    ru1c = models.DecimalField(max_digits=10, decimal_places=2, blank=True, null=True)
    ru1d = models.DecimalField(max_digits=10, decimal_places=2, blank=True, null=True)
    ru1e = models.DecimalField(max_digits=10, decimal_places=2, blank=True, null=True)
    ru2a = models.DecimalField(max_digits=10, decimal_places=2, blank=True, null=True)
    ru2b = models.DecimalField(max_digits=10, decimal_places=2, blank=True, null=True)
    ru2d = models.DecimalField(max_digits=10, decimal_places=2, blank=True, null=True)
    ru2e = models.DecimalField(max_digits=10, decimal_places=2, blank=True, null=True)
    ru2f = models.DecimalField(max_digits=10, decimal_places=2, blank=True, null=True)
    ru3b = models.DecimalField(max_digits=10, decimal_places=2, blank=True, null=True)
    ru3c = models.DecimalField(max_digits=10, decimal_places=2, blank=True, null=True)
    ru3d = models.DecimalField(max_digits=10, decimal_places=2, blank=True, null=True)
    ru4a = models.DecimalField(max_digits=10, decimal_places=2, blank=True, null=True)
    ru4b = models.DecimalField(max_digits=10, decimal_places=2, blank=True, null=True)

from django.contrib.auth.models import User

class UserActivity(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    action = models.CharField(max_length=255,null=True)
    login_time = models.DateTimeField(null=True, blank=True)
    logout_time = models.DateTimeField(null=True, blank=True)
    button_clicked = models.CharField(max_length=255, null=True, blank=True)
    file_downloaded = models.FileField(upload_to='downloads/', null=True, blank=True)
    file_details = models.TextField(null=True, blank=True)
    timestamp = models.DateTimeField(null=True, blank=True)

    def str(self):
        return f"{self.user.username} - {self.action}"