# Generated by Django 5.0.3 on 2024-09-05 09:44

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finalsheet', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useractivity',
            name='action',
        ),
        migrations.RemoveField(
            model_name='useractivity',
            name='button_clicked',
        ),
        migrations.RemoveField(
            model_name='useractivity',
            name='file_details',
        ),
        migrations.RemoveField(
            model_name='useractivity',
            name='login_time',
        ),
        migrations.RemoveField(
            model_name='useractivity',
            name='logout_time',
        ),
        migrations.AlterField(
            model_name='useractivity',
            name='timestamp',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
