# Generated by Django 5.0.3 on 2024-09-05 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finalsheet', '0002_remove_useractivity_action_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useractivity',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
