# Generated by Django 5.0.3 on 2024-09-05 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finalsheet', '0003_alter_useractivity_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='useractivity',
            name='action',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='useractivity',
            name='button_clicked',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='useractivity',
            name='file_details',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='useractivity',
            name='login_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='useractivity',
            name='logout_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='useractivity',
            name='timestamp',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
