# Generated by Django 5.0.3 on 2024-10-28 08:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finalsheet', '0004_useractivity_action_useractivity_button_clicked_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useractivity',
            name='action',
        ),
        migrations.RemoveField(
            model_name='useractivity',
            name='button_clicked',
        ),
        migrations.RemoveField(
            model_name='useractivity',
            name='file_details',
        ),
        migrations.RemoveField(
            model_name='useractivity',
            name='login_time',
        ),
        migrations.RemoveField(
            model_name='useractivity',
            name='logout_time',
        ),
    ]
