# Generated by Django 5.2.4 on 2025-07-15 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finalsheet', '0005_remove_useractivity_action_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='useractivity',
            name='enquiry_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
