# Generated by Django 5.0.3 on 2025-09-24 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finalsheet', '0006_useractivity_enquiry_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='useractivity',
            name='enquiry_number1',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='useractivity',
            name='enquiry_number2',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='useractivity',
            name='enquiry_number3',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
